/* Each new term in the Fibonacci sequence is generated by adding the previous
 two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed
 four million, find the sum of the even-valued terms.
 */

var i = 1,
    j = 2,
    sum = 2;

while(j < 4000000) {
    var k = j;
    j += i;   // Updating j to take up the next Fibonacci Sequence Number by adding its previous number with its current value
    i = k;    // Updating i to take up the next consecutive number (which is the previous value of j)


    if ((j % 2) === 0) {
        sum += j;
    }
}
console.log('Total Sum of even numbered Fibonacci sequence less that 4 million is :' + sum);
